baseURL: "https://kevinalavik.github.io/"
title: "Kevin's Blog"
pagination:
  pagerSize: 5

theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Kevin's Blog"
  description: "Kevin Alavik's personal blog about tech, coding, and projects."
  keywords: [Blog]
  author: "Kevin Alavik"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
  
  homeInfoParams:
    Title: "👋 Welcome to my blog!"
    Content: "Hello, I'm **Kevin Alavik**, a **hobbyist operating system developer** from **Sweden**. I specialize in low-level programming and have a deep interest in the inner workings of computers and software. Through this blog, I share my thoughts, experiences, and occasional rants on topics like **tech**, **programming**, and **operating systems**. Feel free to explore my posts as I delve into the world of **low-level development**."

  socialIcons:
    - name: github  
      url: "https://github.com/kevinalavik"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/19022062/kevin-alavik"
    - name: paypal
      url: "https://www.paypal.me/kevinalavik"
    - name: discord
      url: "https://discord.com/users/1182552623182790660"
    - name: rss
      url: "https://kevinalavik.github.io/posts/index.xml"

  editPost:
    URL: "https://github.com/kevinalavik/blog/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    style: monokai
